version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn project1.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app:ro
    depends_on:
      - db
    env_file:
      - ./.env.web

  db:
    image: postgres:12
    restart: always
    volumes:
      - project2-postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.pg-admin

  pgadmin:
    container_name: pgadmin_2
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env.prod.pg-admin
    ports:
      - "5050:80"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  project2-postgres_data_dev:
